### ISSUE TITLE
[Admin ONG/Evaluare ONG] ''Rezultate pe dimensiuni'' section doesn't exist

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/crestem-ong#68]
Implement ''Rezultate pe dimensiuni'' section in the evaluation page ([see design here](https://www.figma.com/file/EeUtizbTE8Bkqhjx70CwOB/Cre%C8%99tem-ONG?type=design&node-id=750-28754&mode=design&t=2j7lV2ebGW5eue0g-4))

**Comment by teodoranegru** [comment]
Is the same component displayed in the evaluation page for the admin fdsc user but I can't access it due to issue #55

**Comment by cipick** [comment]
should be fixed now

**Comment by teodoranegru** [comment]
still not displayed 

![image](https://github.com/code4romania/crestem-ong/assets/102228836/975b495c-f4bb-4716-99e0-88be075ec9de)

**Comment by cipick** [comment]
<img width="1265" alt="Screenshot 2023-09-28 at 00 57 28" src="https://github.com/code4romania/crestem-ong/assets/6429818/97efc14e-b9b3-4dca-b367-a7cb000196bc">
now it should be fixed 😄
